### ISSUE TITLE
HIFI Kill Error

### ISSUE THREAD

**Issue by 14stutzmanav** [BlanchetteLab/HIFI#5]
Hello there,

I was hoping you could help resolve the following error I experience when I attempt to run 'src/HIFI' on my own dataset. It's worth noting that I have been able to execute this step for the example dataset referenced in READ.me. In short, I am getting a kill error when HIFI reads my sparse matrix (which was generated using BAMtoSparseMatrix.py.

```
> src/HIFI HIFI_output/foo.RF.tsv HIFI_output/foo.RF.HIFI_MRF.tsv -method=mrf
HIFI version 1.0
option -method= mrf
option -fragmentsPerBin= 1
option -kdeMinCount = 50
option -kdeBandwidth = 20.000000
option -kdeMaxBandwidth = 25.000000
option -mrfMaxIter = 5
option -minSigma = 0.001000
option -sigmaMultiplier = 0.040000
option -minSigma = 0.001000
option -firstRow = -1
option -lastRow = -1
option -firstCol = -1
option -lastCol = -1
option -boundaryKS = 2.000000
option -minOutput = 0.000010
option -outputNotNormalized = 0
option -bandSize = 99999999
Reading matrix
Killed: 9
```

Thank you so much!

**Comment by ccameron** [comment]
The sparse matrix being read into memory may be too large and the HIFI process is being killed by the scheduler. The provided example datasets are chromosome subsets and shouldn't require a lot of memory.
